### ISSUE TITLE
Submitting New Version For Review Always Fails 

### ISSUE THREAD

**Issue by anasanasanas** [ferPrieto/steps-app-gallery-deploy#18]
Submitting New Version For Review Always Fails 
Similer issue: https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect/issues/30#issuecomment-990740313
![image](https://user-images.githubusercontent.com/3528063/145649735-183452b4-82a8-436f-a1ed-79677179928a.png)

**Comment by ferPrieto** [comment]
I've just checked this issue and it seems like the Step is completely fine. 
The issue comes from the `Huawei App Gallery: Publish API` **flakiness** ⚠️ 
I would say try again because the API sometimes retrieves errors like that randomly. There's no much to do on the Step.

And thanks for mentioning the issue raised on the Fastlane plugin (`not official plugin`). Their implementation is wrong, because they simply have a delay to wait until the last call to verify if the app file is completely submitted. 
What **Huawei HQ** recommended (applied in this `verified Bitrise Step`) was to call an endpoint periodically to check whether the submission result is ready (`return code 0`) or it needs to wait another 20" cycle to check this  submission result  again.

**Comment by anasanasanas** [comment]
thank you so much for the explanation @ferPrieto
