### ISSUE TITLE
exit code: 26

### ISSUE THREAD

**Issue by s-hulenko** [ferPrieto/steps-app-gallery-deploy#22]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/70511106/152396711-373008b0-c5e4-4894-bc95-ba7d3f996517.png">

**Comment by SeleznevAM** [comment]
I have the same issue.

**Comment by ferPrieto** [comment]
Hey @OlegTranzzo thanks for reporting this issue. It seems like there's some error when uploading the file.

I would need more details in order to give you the exact reason. Would you mind to list the error traces you get?
In the meantime, would you mind to double check the next two requirements and validate whether your file follows that or exceeds any?:
- File size:
```
APK file: The size cannot exceed 4 GB.
RPK file: The size cannot exceed 20 MB.
AAB file: The size cannot exceed 150 MB.
```
- The file name is coherent when it comes to what it's expected: you could be setting a file name with `.apk`
 and gradle would be building an `.aab`. You can check this value in your Huawei Step (within your workflow) 👇🏽 
<p align="center">
<img src="https://user-images.githubusercontent.com/5220412/153673085-c3afe7f9-2eab-49c3-a67a-139cd28561e8.png"/> 
</p>

**Comment by SeleznevAM** [comment]
I have resolved this issue for myself. The reason of it was in that i build apk file but tried to apload aab file. And script couldn't determine file suffix.

**Comment by ferPrieto** [comment]
Cool, I presumed it was some issue between the file format expected and the actual one. 
I will proceed to close this issue then 😄
